apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- redis-kustomization.yaml
patches:
- patches:
  - op: replace
    path: /spec/type
    value: NodePort
  target:
    kind: Service
    name: rec-ui
    namespace: redis
